Args = --initialize-at-run-time=com.salesforce.zsync \
       --initialize-at-build-time=oracle.sql.ConverterArchive \
       --initialize-at-build-time=oracle.sql.converter.CharacterConverterJDBC \
       --initialize-at-build-time=oracle.sql.converter.CharacterConverter1Byte \
       --initialize-at-build-time=oracle.sql.CharacterSet \
       --initialize-at-build-time=oracle.sql.CharacterSetByte \
       --initialize-at-build-time=oracle.sql.CharacterSet1Byte \
       --initialize-at-build-time=oracle.sql.CharacterSet12Byte \
       --initialize-at-build-time=oracle.sql.CharacterSet2ByteFixed \
       --initialize-at-build-time=oracle.sql.CharacterSetWithConverter \
       --initialize-at-build-time=oracle.sql.CharacterSetLCFixed \
       --initialize-at-build-time=oracle.sql.CharacterSetShift \
       --initialize-at-build-time=oracle.sql.CharacterSetUnknown \
       --initialize-at-build-time=oracle.sql.CharacterSetAL32UTF8 \
       --initialize-at-build-time=oracle.sql.CharacterSetUTF \
       --initialize-at-build-time=oracle.sql.CharacterSetUTFE \
       --initialize-at-build-time=oracle.sql.CharacterSetAL16UTF16 \
       --initialize-at-build-time=oracle.sql.CharacterSetAL16UTF16LE \
       --initialize-at-build-time=oracle.sql.CharacterSetGB18030 \
       --initialize-at-build-time=oracle.sql.CharacterSetJAEUC \
       --initialize-at-build-time=oracle.sql.CharacterSetSJIS \
       --initialize-at-build-time=oracle.sql.CharacterSetZHTEUC \
       --initialize-at-build-time=oracle.sql.CharacterSetFactory \
       --initialize-at-build-time=oracle.sql.CharacterSetFactoryDefault \
       --initialize-at-build-time=oracle.sql.CharacterSetFactoryThin \
       --allow-incomplete-classpath \
       -H:+ReportExceptionStackTraces \
       --add-opens java.base/java.util.zip=ALL-UNNAMED
